### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by refset** [xtdb/learn-xtdb-datalog-today#15]
- [ ] Sanity check answers side-by-side against the original materials
- [x] Check original GitHub issues/PRs for unaddressed mistakes/errors/improvements
- [x] Spelling and grammar check
- [x] General comprehension improvements / feedback / discussion

**Comment by refset** [comment]
> Sanity check answers side-by-side against the original materials

Got bit by failing to do this in https://github.com/xtdb/learn-xtdb-datalog-today/issues/16 :/
